### ISSUE TITLE
vmtkcenterlines error when running aneurysm removal demo

### ISSUE THREAD

**Issue by myousefi2016** [KVSlab/morphMan#52]
I installed morphMan by using this command in my system with Anaconda3/5.1.0:

```
conda create -n sac-analysis -c vmtk -c morphman morphman
```

Then I run the demo by using this command:

```
 morphman-bifurcation --ifile C0066/surface/model.vtp --ofile C0066/surface/removed_aneurysm.vtp --keep-fixed-1 True --keep-fixed-2 True --bif True --lower True --angle 0 --region-of-interest commandline --region-points 31.37 60.65 25.21 67.81 43.08 41.24 --poly-ball-size 250 250 250
```

But I'm getting this error:

```
-- Region of interest is defined by the region points: 
Outlet 1: (31.371356964111328, 60.65427780151367, 25.212461471557617) 
Outlet 2: (67.81478881835938, 43.07576370239258, 41.239501953125)
Cleaning surface.
Triangulating surface.
Traceback (most recent call last):
  File "/home/yousefi/.conda/envs/sac-analysis/bin/morphman-bifurcation", line 11, in <module>
    load_entry_point('morphman==1.0', 'console_scripts', 'morphman-bifurcation')()
  File "/home/yousefi/.conda/envs/sac-analysis/lib/python3.6/site-packages/morphman-1.0-py3.6.egg/morphman/manipulate_bifurcation.py", line 652, in main_bifurcation
  File "/home/yousefi/.conda/envs/sac-analysis/lib/python3.6/site-packages/morphman-1.0-py3.6.egg/morphman/manipulate_bifurcation.py", line 97, in manipulate_bifurcation
  File "/home/yousefi/.conda/envs/sac-analysis/lib/python3.6/site-packages/morphman-1.0-py3.6.egg/morphman/common/surface_operations.py", line 712, in compute_centerlines
  File "/home/yousefi/.conda/envs/sac-analysis/lib/python3.6/site-packages/morphman-1.0-py3.6.egg/morphman/common/vmtk_wrapper.py", line 91, in vmtk_compute_centerlines
  File "/home/yousefi/.conda/envs/sac-analysis/lib/python3.6/site-packages/vmtk/vmtkcenterlines.py", line 595, in Execute
    self.SeedSelector.Execute()
  File "/home/yousefi/.conda/envs/sac-analysis/lib/python3.6/site-packages/vmtk/vmtkcenterlines.py", line 128, in Execute
    for i in range(len(self.SourcePoints)/3):
TypeError: 'float' object cannot be interpreted as an integer
```

Any idea how to fix it?

**Comment by hkjeldsberg** [comment]
Hi! Yes, this is known issue with the currently distributed version of VMTK (1.4) on Anaconda.

As a workaround you have to change two lines in `vmtkcenterlines.py`. This can be done by running the two following commands in the temrinal:

```
sed -i -e 's/len(self.SourcePoints)\/3/len\(self.SourcePoints\)\/\/3/g' /home/yousefi/.conda/envs/sac-analysis/lib/python3.6/site-packages/vmtk/vmtkcenterlines.py
```
```
sed -i -e 's/len(self.TargetPoints)\/3/len\(self.TargetPoints\)\/\/3/g' /home/yousefi/.conda/envs/sac-analysis/lib/python3.6/site-packages/vmtk/vmtkcenterlines.py
```

For reference we have added a warning in the installation guide for this particular issue: https://morphman.readthedocs.io/en/latest/installation.html

**Comment by myousefi2016** [comment]
@hkjeldsberg Thanks! It worked!
