### ISSUE TITLE
Error using Manipulate Area on geometry with multiple inlets and outlets

### ISSUE THREAD

**Issue by DucoG** [KVSlab/morphMan#54]
I installed Morphman to inflate a vascular section. However, when I try to apply any script to the geometry, I get the following error:
```
morphman-area --ifile veloc6.vtp --ofile veloc6vs.vtp --method area --percentage 20 --region-of-interest first_line --poly-ball-size 250 250 250
Traceback (most recent call last):
  File "C:\Users\ducog\Anaconda3\envs\morhpman-env\Scripts\morphman-area-script.py", line 10, in <module>
    load_entry_point('morphman==1.0', 'console_scripts', 'morphman-area')()
  File "C:\Users\ducog\Anaconda3\envs\morhpman-env\lib\site-packages\morphman-1.0-py3.6.egg\morphman\manipulate_area.py", line 572, in main_area
  File "C:\Users\ducog\Anaconda3\envs\morhpman-env\lib\site-packages\morphman-1.0-py3.6.egg\morphman\manipulate_area.py", line 79, in manipulate_area
  File "C:\Users\ducog\Anaconda3\envs\morhpman-env\lib\site-packages\morphman-1.0-py3.6.egg\morphman\common\centerline_operations.py", line 296, in get_line_to_change
  File "C:\Users\ducog\Anaconda3\envs\morhpman-env\lib\site-packages\morphman-1.0-py3.6.egg\morphman\common\centerline_operations.py", line 251, in get_centerline_tolerance
ValueError: operands could not be broadcast together with shapes (2,) (3,)
```

The error seems to be with the geometry, as I do get results when using other geometries. I've attached an image of the geometry. Anyone who knows how I could solve the issue?

![picture_tcpc](https://user-images.githubusercontent.com/67788719/86474893-03f47680-bd44-11ea-92a3-baa8b612b086.png)

**Comment by aslakbergersen** [comment]
Hi @DucoG,

Thank you for using morhpMan and reporting your issue. I would be happy to help you fix this problem. Would it be possible for you to share the geometry such that I can debug the problem and potentially create a patch to make it work? You could clip the geometry after the first three outlets if you do not want to share the entire geometry, I'm guessing that still reproduces the error.

**Comment by DucoG** [comment]
Hi @aslakbergersen 

That would be great! Could I perhaps send the geometry to you personally?

**Comment by hkjeldsberg** [comment]
Hi @DucoG!

If you still need help with your issue, I can be of your assistance. Otherwise, I will consider closing this issue, unless there is any follow-up.
