### ISSUE TITLE
pip install gives UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by johannesring** [KVSlab/morphMan#64]
When trying to install morhpMan I get the following error:
```
$ pip3 install .
Processing /tmp/morphMan
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-mjkkli3s-build/setup.py", line 4, in <module>
        long_description = fh.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2365: ordinal not in range(128)
```
This patch fixes the problem:
``` patch
diff --git a/setup.py b/setup.py
index 0d51ed3..8ba08ad 100644
--- a/setup.py
+++ b/setup.py
@@ -1,6 +1,6 @@
 import setuptools
 
-with open("README.md", "r") as fh:
+with open("README.md", "r", encoding="utf-8") as fh:
     long_description = fh.read()
 
 DEPENDENCIES = []  # 'scipy', 'numpy', 'vtk']
```

**Comment by hkjeldsberg** [comment]
Thanks for noticing us, and suggesting a fix! 👍 
The fix has been added in #63.
