### ISSUE TITLE
A value error when using morphman-area

### ISSUE THREAD

**Issue by JIsaacW** [KVSlab/morphMan#82]
Hi, I'm new in morphman,
When I use `morphman-area` command to adjust a coronary geometry model, there is an error like this:
```
Please select region of interest in the render window.
Quit renderer
-- The chosen region points: [-3.548530340194702, 1.9141699075698853, -15.790369987487793]
Traceback (most recent call last):
  File "/home/isaac/Program/anaconda3/envs/morphman/bin/morphman-area", line 10, in <module>
    sys.exit(main_area())
  File "/home/isaac/Program/anaconda3/envs/morphman/lib/python3.10/site-packages/morphman/manipulate_area.py", line 572, in main_area
    manipulate_area(**read_command_line_area())
  File "/home/isaac/Program/anaconda3/envs/morphman/lib/python3.10/site-packages/morphman/manipulate_area.py", line 76, in manipulate_area
    centerline_splined, centerline_remaining, centerline_diverging, region_points, diverging_ids = get_line_to_change(
  File "/home/isaac/Program/anaconda3/envs/morphman/lib/python3.10/site-packages/morphman/common/centerline_operations.py", line 479, in get_line_to_change
    line_to_change = compute_splined_centerline(line_to_change, nknots=nknots, isline=True)
  File "/home/isaac/Program/anaconda3/envs/morphman/lib/python3.10/site-packages/morphman/common/centerline_operations.py", line 761, in compute_splined_centerline
    fx = splrep(curv_coor, data[:, 0], k=4, t=t)
  File "/home/isaac/Program/anaconda3/envs/morphman/lib/python3.10/site-packages/scipy/interpolate/_fitpack_py.py", line 288, in splrep
    res = _impl.splrep(x, y, w, xb, xe, k, task, s, t, full_output, per, quiet)
  File "/home/isaac/Program/anaconda3/envs/morphman/lib/python3.10/site-packages/scipy/interpolate/_fitpack_impl.py", line 508, in splrep
    raise _iermess[ier][1](_iermess[ier][0])
ValueError: Error on input data
```
This is my input:
```
morphman-area -i model.vtp -o symmetry_stenosis.vtp -b 250 250 250 -m stenosis -r manual --size 2.0 -p 50
```
How can I solve this error, thanks!

**Comment by hkjeldsberg** [comment]
Hi @JIsaacW,

Thanks for reporting this issue. Seems to be an issue when splining the centerline, so perhaps it is related to the input centerline. 

Could you possibly share the geometry you are using for manipulation? 

Best regard,
Henrik
